# Generated by Django 5.2.1 on 2025-06-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fee_households_fee_is_common'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residencyrequest',
            name='request_type',
            field=models.CharField(choices=[('temporary_absence', 'Tạm vắng'), ('temporary_residence', 'Tạm trú')], max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('chu_ho', 'Head of Household'), ('thu_ky', 'Accountant'), ('to_truong', 'Group Leader'), ('to_pho', 'Vice Group Leader')], max_length=20),
        ),
    ]
